# Generated by Django 5.1.4 on 2024-12-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_audiofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
