# Generated by Django 5.1.4 on 2025-01-02 10:12

import django.db.models.deletion
from django.db import migrations, models


def create_default_category(apps, schema_editor):
    # Get the Category model from the historical models
    Category = apps.get_model('api', 'Category')
    # Create the default category
    default_category = Category.objects.create(name='Uncategorized')
    return default_category.id


def set_default_category(apps, schema_editor):
    # Assign the default category to existing audio files
    Category = apps.get_model('api', 'Category')
    AudioFile = apps.get_model('api', 'AudioFile')
    default_category = Category.objects.get(name='Uncategorized')
    AudioFile.objects.filter(category__isnull=True).update(category=default_category)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='audiofile',
            name='category',
            field=models.ForeignKey(
                null=True,  # Allow null initially for existing records
                blank=True,  # Allow blank for form submissions
                on_delete=django.db.models.deletion.CASCADE,
                related_name='audio_files',
                to='api.category',
            ),
        ),
        migrations.RunPython(
            create_default_category,  # Create the default category
            reverse_code=migrations.RunPython.noop  # No reverse operation needed
        ),
        migrations.RunPython(
            set_default_category,  # Assign the default category to existing audio files
            reverse_code=migrations.RunPython.noop  # No reverse operation needed
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='audio_files',
                to='api.category',
            ),
        ),
    ]
