# Generated by Django 5.1.4 on 2025-01-03 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_audiofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.category'),
        ),
    ]
